services:
  router-node:
    platform: linux/amd64
    image: "${TENSORS_ROUTER_ROCM_NODE_IMAGE:-ghcr.io/derijans/tensors-router/tensors-router-node-rocm:latest}"
    build:
      context: ..
      dockerfile: Containerfile
      target: node-rocm
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add: ["video", "render"]

  router-webui:
    platform: linux/amd64
    image: "${TENSORS_ROUTER_ROCM_WEBUI_IMAGE:-ghcr.io/derijans/tensors-router/tensors-router-webui-rocm:latest}"
    build:
      context: ..
      dockerfile: Containerfile
      target: webui-rocm
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add: ["video", "render"]
